-- P3-1 发票三单匹配（旗舰）：发票实体 + 匹配结果/解释 JSON
CREATE TABLE invoice (
    id varchar(32) PRIMARY KEY,
    order_id varchar(32) NOT NULL REFERENCES purchase_order(id) ON DELETE CASCADE,
    invoice_code varchar(64) NULL,
    invoice_no varchar(64) NOT NULL,
    issue_date date NULL,
    quantity decimal(60,18) NULL,
    unit varchar(50) NULL,
    unit_price decimal(60,18) NULL,
    amount_excluding_tax decimal(60,18) NULL,
    tax_amount decimal(60,18) NULL,
    total_amount decimal(60,18) NOT NULL,
    tax_rate decimal(10,6) NULL,
    supplier_name varchar(300) NOT NULL,
    artifact_id varchar(36) NOT NULL,
    source_sha256 varchar(64) NOT NULL,
    parser_version varchar(100) NOT NULL,
    status varchar(30) NOT NULL,
    match_result json NULL,
    match_explanation json NULL,
    notes varchar(2000) NULL,
    version bigint NOT NULL DEFAULT 0,
    created_at datetime(6) NOT NULL,
    updated_at datetime(6) NOT NULL,
    matched_at datetime(6) NULL,
    reconciled_at datetime(6) NULL,
    UNIQUE KEY uq_invoice_no (invoice_no),
    KEY idx_invoice_order (order_id, created_at),
    KEY idx_invoice_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
