KafkaServer {
  org.apache.kafka.common.security.scram.ScramLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_java-svc="java-secret"
  user_python-agent="python-secret";
};